name: docker & singularity/cvmfs releases

on:
  push:
    # on push tags only
    branches-ignore:
      - '**'
    tags:
      - '**'
  workflow_dispatch:
  delete:
    branches:
      - '**'

jobs:
  image-publish:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@v1.16
    permissions: # for GITHUB_TOKEN
      packages: write
    with:
      image_registry: ghcr.io
      image_namespace: observation-management-service
      image_name: ewms-pilot
      mode: ${{ github.event_name == 'delete' && 'CVMFS_REMOVE' || 'CVMFS_BUILD' }}
      cvmfs_dest_dir: ewms/observation-management-service  # in heinsight, this is verbose but we've got to live with it
      # only used if mode is CVMFS_REMOVE:
      cvmfs_remove_tags: '${{ github.event.ref }}-[SHA]'
      # only used if mode builds image:
      build_args: CONTAINER_PLATFORM=apptainer
    secrets:
      cvmfs_github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
