name: docker & singularity/cvmfs releases

on:
  push:
    # on push tags only
    branches-ignore:
      - '**'
    tags:
      - '**'
  workflow_dispatch:
  delete:
    branches:
      - '**'

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAMESPACE: observation-management-service
  IMAGE_NAME: ewms-pilot

jobs:

  image-publish-apptainer:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@v1.17
    permissions: # for GITHUB_TOKEN
      packages: write
    with:
      image_registry: ${{ env.IMAGE_REGISTRY }}
      image_namespace: ${{ env.IMAGE_NAMESPACE }}
      image_name: ${{ env.IMAGE_NAME }}
      mode: ${{ github.event_name == 'delete' && 'CVMFS_REMOVE' || 'CVMFS_BUILD' }}
      cvmfs_dest_dir: ewms/observation-management-service  # in heinsight, this is verbose but we've got to live with it
      # only used if mode is CVMFS_REMOVE:
      cvmfs_remove_tags: '${{ github.event.ref }}-[SHA]'
      # only used if mode builds image:
      build_args: CONTAINER_PLATFORM=apptainer
      # no 'tag_suffix' -- this will point to the default (suffix-less) tag
    secrets:
      cvmfs_github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  image-publish-docker:
    if: github.event_name != 'delete'
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@v1.17
    permissions: # for GITHUB_TOKEN
      packages: write
    with:
      image_registry: ${{ env.IMAGE_REGISTRY }}
      image_namespace: ${{ env.IMAGE_NAMESPACE }}
      image_name: ${{ env.IMAGE_NAME }}
      mode: 'BUILD'
      build_args: CONTAINER_PLATFORM=docker
      tag_suffix: docker
